# Generated by Django 4.2.2 on 2023-07-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=200)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_need_repair', models.BooleanField(default=False)),
                ('is_zeroed', models.BooleanField(default=True)),
                ('item_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.license')),
            ],
        ),
    ]
