# Generated by Django 4.2.2 on 2023-06-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponitem',
            name='item_license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.license'),
        ),
    ]
